version: 2.1

params: &params
  parameters:
    node_version:
      type: string
      default: '14'
    jdk_version:
      type: string
      default: '8.0.292.j9-adpt'
    sbt_version:
      type: string
      default: '1.5.5'
    semantic_release_version:
      type: string
      default: '17'

test_matrix: &test_matrix
  matrix:
    parameters:
      node_version:
        - '12'
        - '14'
        - '16'
      jdk_version:
        - '8.0.292.j9-adpt'
        - '11.0.11.j9-adpt'
      sbt_version:
        - '1.5.5'
        - '1.7.0'
jobs:
  test:
    <<: *params
    docker:
      - image: circleci/node:<<parameters.node_version>>
    steps:
      - checkout
      - run:
          name: Install sdkman
          command: |
            curl -s "https://get.sdkman.io?rcupdate=false" | bash
            echo -e '\nsource "/home/circleci/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install JDK <<parameters.jdk_version>>
          command: sdk install java <<parameters.jdk_version>>
      - run:
          name: Install sbt << parameters.sbt_version >>
          command: sdk install sbt <<parameters.sbt_version>>
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
      - store_test_results:
          path: ./coverage
  release:
    <<: *params
    resource_class: small
    docker:
      - image: circleci/node:<<parameters.node_version>>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Release
          command: npx semantic-release@<<parameters.semantic_release_version>>

workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          name: Test node=<<matrix.node_version>> jdk=<<matrix.jdk_version>> sbt=<<matrix.sbt_version>>
          context: nodejs-install
          <<: *test_matrix
          filters:
            branches:
              ignore:
                - master
      - release:
          name: Release
          context: nodejs-app-release
          filters:
            branches:
              only:
                - master
